<a href="https://colab.research.google.com/github/JuarezEmmanuel/Data-Science-Python/blob/main/clase_2_Python_B%C3%A1sico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tipos de Variables en Python

- **Variable de Caracter**: Es un tipo de variable que almacena un solo carácter. Se define utilizando comillas simples o dobles alrededor del carácter.

```python
caracter = 'a'


In [ ]:
caracter = "a"
print(caracter)

a


Lista: Es una colección ordenada y mutable de elementos. Se define utilizando corchetes []

In [ ]:
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

Tupla: Es similar a una lista pero inmutable, es decir, no se puede modificar una vez creada. Se define utilizando paréntesis ().

In [ ]:
tupla = (1, 2, 3, 4, 5)
tupla

(1, 2, 3, 4, 5)

Diccionario: Es una colección de pares clave-valor no ordenados y mutables. Se define utilizando llaves {} y separando cada par clave-valor con :.

In [ ]:
diccionario = {'nombre': 'Juan', 'edad': 30, 'ciudad': 'Madrid'}
diccionario

{'nombre': 'Juan', 'edad': 30, 'ciudad': 'Madrid'}

Set: Es una colección no ordenada y sin elementos duplicados. Se define utilizando llaves {}.

In [ ]:
conjunto = {1, 2, 3, 4, 5} #investigar
conjunto

{1, 2, 3, 4, 5}

##**Estructuras de Control en Python**
**if: Permite ejecutar un bloque de código si una condición es verdadera.**

In [ ]:
x = 4
if x > 5:
  print("x es mayor que 5")
else:
  print("x es menor o igual que 5")

x es menor o igual que 5


for: Permite iterar sobre los elementos de una secuencia (como una lista o tupla) o cualquier objeto iterable.

In [ ]:
for i in range(1, 7):
    print(i)


1
2
3
4
5
6


In [ ]:
numeros = [1, 2, 3, 4, 5]
for i in numeros:
    print(i)


1
2
3
4
5


while: Permite ejecutar un bloque de código mientras una condición sea verdadera.

In [ ]:
contador = 0
while contador <5:
    print(contador)
    contador = contador + 1


0
1
2
3
4



# **Markdown** 🛠️

**Markdown** es un lenguaje de marcado ligero que se utiliza para formatear texto de manera sencilla y rápida. Fue creado con la idea de que sea fácil de leer y escribir, incluso sin procesadores de texto complejos.


💡 Algunas de las características más comunes de Markdown incluyen:

 ✔️ La capacidad de crear títulos y subtítulos con diferentes niveles de encabezado.
- ✨ Formateo de texto como **negrita**, *cursiva* y ~~tachado~~.
- 📋 Creación de listas ordenadas y no ordenadas.
- 🔗 Inclusión de [enlaces](https://example.com) e imágenes.
- 🖥️ Creación de bloques de código.
- 📊 Soporte para tablas.

Markdown se utiliza ampliamente en diferentes plataformas, como en la documentación de proyectos de software, en foros, en la creación de blogs y, por supuesto, en la creación de contenido en **Jupyter Notebooks**. 🚀


## Función en Programación

Una función en programación es un bloque de código que realiza una tarea específica cuando es llamado o invocado desde otra parte del programa. Estas funciones pueden tomar argumentos como entrada, realizar algún procesamiento y devolver un resultado o realizar alguna acción. Las funciones permiten modularizar el código, lo que significa que puedes escribir una vez la lógica de una tarea y reutilizarla múltiples veces en diferentes partes de tu programa. 🔄

### Sintaxis Básica

En Python, la sintaxis básica para definir una función es la siguiente:

```python
def nombre_funcion(parametros):
    # Código de la función
    return resultado


In [ ]:
def sumar(a, b):
    resultado = a + b
    return resultado

# Llamamos a la función sumar
resultado_suma = sumar(10000, 1500)
print(resultado_suma)  # Esto imprimirá

11500


**Doble Divertido 🎲**
Enunciado del Problema: Queremos calcular el doble de un número. ¡Tu tarea es escribir una función que tome un número y devuelva el doble de ese número!

Instrucciones:

Escribe una función llamada calcular_doble que tome un número como entrada.
La función debe devolver el doble de ese número.
Prueba tu función con diferentes números y muestra el resultado.

In [ ]:
def calcular_doble(numero):
    """Calcula el doble de un número."""
    return numero * 2

# Prueba del ejercicio
resultado = calcular_doble(8)
print("El doble de 8 es:", resultado)

El doble de 8 es: 16


**Cuadrado Curioso 📐**
Enunciado del Problema: ¿Quieres conocer el secreto del cuadrado? ¡Vamos a calcular el cuadrado de un número! Tu tarea es escribir una función que tome un número y devuelva su cuadrado.

Instrucciones:

Escribe una función llamada calcular_cuadrado que tome un número como entrada.
La función debe devolver el cuadrado de ese número.
Prueba tu función con diferentes números y muestra el resultado.

In [ ]:
def calcular_cuadrado(numero):
    """Calcula el cuadrado de un número."""
    return numero ** 2

# Prueba del ejercicio
resultado = calcular_cuadrado(3)
print("El cuadrado de 3 es:", resultado)


El cuadrado de 3 es: 9


Problema 1: 🎲 Dados Divertidos 🎲
Enunciado del Problema: Queremos simular el lanzamiento de dos dados y contar cuántas veces obtenemos una suma par.

In [ ]:
import random

def lanzar_dados_y_contar_suma_par(num_lanzamientos):
    """
    Simula el lanzamiento de dos dados y cuenta cuántas veces obtenemos una suma par.

    Parameters:
    num_lanzamientos: El número de lanzamientos de dados a simular.

    Returns:
    La cantidad de veces que la suma de los dados fue par.
    """
    suma_par = 0  # Inicializamos un contador para la suma par
    for _ in range(num_lanzamientos):  # Iteramos sobre el número de lanzamientos
        dado1 = random.randint(1, 6)  # Generamos el resultado del primer dado
        dado2 = random.randint(1, 6)  # Generamos el resultado del segundo dado
        suma = dado1 + dado2  # Calculamos la suma de los resultados
        if suma % 2 == 0:  # Verificamos si la suma es par
            suma_par += 1  # Incrementamos el contador si la suma es par
    return suma_par  # Devolvemos la cantidad de sumas pares

# Simulamos 100 lanzamientos y contamos la cantidad de veces que la suma es par
num_lanzamientos = 100
resultado = lanzar_dados_y_contar_suma_par(num_lanzamientos)
print(f"De {num_lanzamientos} lanzamientos, {resultado} veces la suma fue par.")

De 100 lanzamientos, 46 veces la suma fue par.


Problema del Máximo Número 🚀
Enunciado del Problema: Queremos encontrar el número más grande en una lista de números. ¡Tu tarea es escribir una función que encuentre este número máximo! 📊

Instrucciones:

Escribe una función llamada encontrar_maximo que tome una lista de números como entrada.
Esta función debe devolver el número más grande de la lista.
¡Pon a prueba tu función con una lista de números y asegúrate de que encuentre correctamente el máximo! 🧐
¡Buena suerte! 🍀

In [ ]:
def encontrar_maximo(lista): # Tarea
    """
    Encuentra el máximo elemento en una lista de números.

    Parameters:
    lista (list): La lista de números.

    Returns:
    int or float: El valor máximo en la lista.
    """
    if not lista:  # Verifica si la lista está vacía
        return None  # Devuelve None si la lista está vacía

    maximo = lista[0]  # Asigna el primer elemento de la lista como el máximo inicialmente

    for num in lista:  # Itera sobre cada número en la lista
        if num > maximo:  # Compara si el número actual es mayor que el máximo actual
            maximo = num  # Si es así, actualiza el valor máximo

    return maximo  # Devuelve el máximo encontrado


# Ejemplo de uso
numeros = [12, 45, 67, 2300, 200, 34, 250]
maximo_numero = encontrar_maximo(numeros)
print(f"El máximo número en la lista es: {maximo_numero}")


El máximo número en la lista es: 2300


##**zip en Python** / TAREA
La función zip en Python toma iterables (objetos que se pueden iterar, como listas, tuplas, etc.) y los combina en una secuencia de tuplas. Cada tupla contiene elementos correspondientes de los iterables originales en el mismo índice. / **TAREA**

In [ ]:
lista1 = [1, 2, 3]
lista2 = ['a', 'b', 'c']

# Usando zip para combinar las listas
resultado = zip(lista1, lista2)

# Mostrando el resultado
print(list(resultado))  # Salida: [(1, 'a'), (2, 'b'), (3, 'c')]

[(1, 'a'), (2, 'b'), (3, 'c')]


### Introducción a Pandas y NumPy 🚀

Pandas es una poderosa biblioteca de Python utilizada para el análisis y manipulación de datos estructurados. Proporciona estructuras de datos flexibles y eficientes, como DataFrames y Series, que permiten trabajar con datos de manera fácil y rápida. Con pandas, puedes cargar, limpiar, transformar y analizar datos de manera efectiva, lo que lo convierte en una herramienta fundamental para científicos de datos y analistas. 🐼📊

NumPy es una biblioteca fundamental para la computación científica en Python. Proporciona una matriz multidimensional (ndarray) eficiente en términos de memoria y operaciones matemáticas rápidas en matrices. NumPy se utiliza ampliamente en el procesamiento de datos, la manipulación de matrices, el álgebra lineal, el cálculo numérico y muchas otras áreas de la computación científica y la ingeniería. Además de su eficiencia, NumPy también proporciona una amplia gama de funciones matemáticas y herramientas para trabajar con datos numéricos de manera efectiva. 🔢🧮


Ejemplo:

In [ ]:
## Numpy

In [ ]:
import numpy as np

# Ejemplo 1: Crear un arreglo unidimensional
arreglo_1d = np.array([1, 2, 3, 4, 5])
print("Arreglo 1D:", arreglo_1d)

# Ejemplo 2: Crear una matriz de ceros de 3x3
matriz_zeros = np.zeros((3, 3))
print("\nMatriz de ceros 3x3:\n", matriz_zeros)

# Ejemplo 3: Crear una matriz identidad de 4x4
matriz_identidad = np.eye(4)
print("\nMatriz Identidad 4x4:\n", matriz_identidad)

# Ejemplo 4: Suma de dos matrices
matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[5, 6], [7, 8]])
matriz_suma = np.add(matriz_a, matriz_b)
print("\nSuma de dos matrices:\n", matriz_suma)

# Ejemplo 5: Multiplicación de matrices
matriz_mult = np.dot(matriz_a, matriz_b)
print("\nMultiplicación de dos matrices:\n", matriz_mult)


Arreglo 1D: [1 2 3 4 5]

Matriz de ceros 3x3:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz Identidad 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Suma de dos matrices:
 [[ 6  8]
 [10 12]]

Multiplicación de dos matrices:
 [[19 22]
 [43 50]]


In [ ]:
import pandas as pd

# Crear un DataFrame de ejemplo
datos = {'Nombre': ['Ana', 'Juan', 'María', 'Pedro', 'Sara'],
         'Edad': [25, 30, 35, 40, 45]}

df = pd.DataFrame(datos, index=['A', 'B', 'C', 'D', 'E'])
df

Nombre  Edad
A    Ana    25
B   Juan    30
C  María    35
D  Pedro    40
E   Sara    45

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1NKPo6qo3gacIqNM3F-09FtWQBQs0cgshtHAFkwGuBS0/edit#gid=0


**Usando loc para seleccionar filas basadas en etiquetas:**

In [ ]:
# Usar loc para seleccionar la fila con etiqueta 'C' y todas las columnas
seleccion_loc = df.loc["C", :]
print("Selección usando loc:")
print(seleccion_loc)


Selección usando loc:
Nombre    María
Edad         35
Name: C, dtype: object


**Usando iloc para seleccionar filas basadas en índices enteros:**

In [ ]:
# Usar iloc para seleccionar la tercera fila y todas las columnas
seleccion_iloc = df.iloc[2, :]
print("\nSelección usando iloc:")
print(seleccion_iloc)



Selección usando iloc:
Nombre    María
Edad         35
Name: C, dtype: object


Atento con este regla ❌ Excluye el límite
✅ Incluye el límite / TAREA

In [ ]:
# Usar loc para seleccionar las filas desde 'B' hasta 'D' (inclusive) y todas las columnas
seleccion_rango_loc = df.loc['B':'D', :]
print("\nSelección de rango usando loc:")
print(seleccion_rango_loc)

# Usar iloc para seleccionar las filas desde la segunda hasta la cuarta (exclusiva) y todas las columnas / COMO HACERLO CON ILOC '?
seleccion_rango_iloc = df.iloc[1:4, :]
print("\nSelección de rango usando iloc:")
print(seleccion_rango_iloc)



Selección de rango usando loc:
  Nombre  Edad
B   Juan    30
C  María    35
D  Pedro    40

Selección de rango usando iloc:
  Nombre  Edad
B   Juan    30
C  María    35
D  Pedro    40


**Calculo de estadistica básica**

In [ ]:
seleccion_rango_loc_edad = df.loc['B':'D', 'Edad']
print("Selección de rango de edades usando loc:")
print(seleccion_rango_loc_edad)


Selección de rango de edades usando loc:
B    30
C    35
D    40
Name: Edad, dtype: int64


In [ ]:
seleccion_rango_iloc_edad = df.iloc[1:4, 1]  # Selecciona las filas 1 a 4 (excluyendo la 4) y solo la columna "Edad" / TAREA
print("Selección de rango de edades usando iloc:") # Tarea
print(seleccion_rango_iloc_edad)


Selección de rango de edades usando iloc:
B    30
C    35
D    40
Name: Edad, dtype: int64


In [ ]:
df

Nombre  Edad
A    Ana    25
B   Juan    30
C  María    35
D  Pedro    40
E   Sara    45

In [ ]:
# Calcular la media edad
media = df['Edad'].mean()

# Calcular la mediana edad
mediana = df['Edad'].median()

# Calcular la moda de las calificaciones
moda = df['Edad'].mode().values[0] #la moda puede tener mas de un valor, con esto nos aseguramos que nos quedemos con el principal

# Calcular la desviación estándar de las calificaciones
desviacion_estandar = df['Edad'].std()

# Mostrar los resultados
print("Media:", media)
print("Mediana:", mediana)
print("Moda:", moda)
print("Desviación Estándar:", desviacion_estandar)


Media: 35.0
Mediana: 35.0
Moda: 25
Desviación Estándar: 7.905694150420948


In [ ]:
df.describe()

Edad
count   5.000000
mean   35.000000
std     7.905694
min    25.000000
25%    30.000000
50%    35.000000
75%    40.000000
max    45.000000

📊 **Enunciado:** / **TAREA**

Un inversor compra acciones cada día de la semana. El precio de las acciones y la cantidad comprada varían diariamente 📈. Considera también una probabilidad de ganancia por día 🎯. Se requiere calcular el valor esperado al final de la semana 💰.

💡 **Input:** Lista de cantidades compradas, lista de precios diarios y la probabilidad de ganancia.


In [ ]:
#def retorno_semanal_simple(cantidad_comprada, valores, probabilidad_ganancia):



        # Valor diario multiplicado por la probabilidad de ganancia y pérdida (1 - probabilidad de ganancia)

        # Aquí usamos '+=', que es lo mismo que escribir valor_esperado = valor_esperado + valor_dia
         # Consideramos que la pérdida es 0
    #se asume que el inversor no pierde dinero, sino que simplemente no obtiene ninguna ganancia adicional.


# Datos de ejemplo


# Calcular el valor esperado

# Mostrar el resultado



**Lectura de un conjunto de datos para sacar media, mediana, moda y desviación estandar**

In [ ]:
#import pandas as pd

# Cargar el conjunto de datos Iris
#df = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')



In [ ]:
#df

In [ ]:
# describe diferente ? como hacerlo

# **Ejercicios** / TAREA

**Calcular el área de un triángulo ⏰**

In [ ]:
#def area_triangulo(base, altura):



**Ejercicio de cálculo de promedio ponderado 📊**
Escribe una función llamada promedio_ponderado que calcule el promedio ponderado de una lista de valores, teniendo en cuenta los pesos y créditos correspondientes. Esta función toma tres listas como entrada: una lista de valores, una lista de pesos y una lista de créditos. Luego, devuelve el promedio ponderado de los valores.

 **Cálculo de Potencia al Cubo 🎲**
Escribe una función llamada potencia_cubo que tome un número como entrada y calcule su potencia al cubo.

**La Fórmula Matemágica Simplificada 🎩✨**
Descubre la versión simplificada de la fórmula matemágica más increíble! Escribe una función llamada formula_matemagica_simplificada que tome tres números como entrada: a, b y c. Esta función debe calcular y devolver el resultado de la siguiente fórmula misteriosa: a^2 + b^2 + c^2 ¡Sigue las instrucciones y desentraña el misterio de esta fórmula matemágica simplificada!








**función para calcular el factorial de un número de forma recursiva:🔮**



Enunciado del ejercicio:
📊 Enunciado:

Un inversor compra una cantidad de acciones específica cada día durante la semana. El precio de las acciones varía diariamente 📈, y se conoce tanto la probabilidad de obtener una ganancia como la probabilidad de incurrir en una pérdida.

💡 Input:

Lista con la cantidad de acciones compradas por día.
Lista con el precio diario de las acciones.
Probabilidad de ganancia y probabilidad de pérdida.
📈 Objetivo: Crear una función que calcule el valor esperado de la inversión al final de la semana, tomando en cuenta tanto las probabilidades de ganancia como de pérdida.

In [ ]:
#def retorno_semanal(cantidad_comprada, valores, probabilidad_ganancia, probabilidad_perdida):

    # Iterar sobre cada día

    #return valor_esperado

# Datos de ejemplo


# Calcular el valor esperado


# Mostrar el resultado

